name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml
    - name: Generate Site
      run: mvn site site:stage
    - name: Archive Site
      uses: actions/upload-artifact@v3
      with:
        name: site
        path: target/staging
    - name: Run Tests
      run: mvn test
    - name: Verify Checkstyle
      run: mvn checkstyle:check
